name: .NET Core
on:
  push:
    branches: [ main ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0
 
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu
        path: bin/publish/
        
  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0
 
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: bin/publish/
        
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0
 
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: bin/publish/